import type { Project } from "~/types";

export const PROJECTS: Project[] = [
  {
    year: 2026,
    name: "Mandario Whitelabel",
    image: "/web_resume/mandario-whitelabel.png",
    text: "B2B e-shop vyvinutý pro společnost Mandario, zaměřený na prodej kosmetických produktů a bytové chemie. Jde o uzavřenou klientskou zónu, kde mohou uživatelé procházet zboží, vytvářet objednávky a sledovat jejich stav. Nejkomplexnější částí aplikace je kaskádový konfigurátor, který umožňuje detailní sestavení produktu na míru (výběr obalu, uzávěru, krabičky či potisku). Kompletně celý frontend aplikace jsem vyvíjel já s využitím frameworku Next.js. Aplikace komunikuje s vlastním backendem pro správu obsahu a využívá Ecomail API pro transakční e-maily.",
    techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
    links: [{ url: "https://konfigurator.mandario.eu", text: "Navšívit web" }],
  },
  {
    year: 2026,
    name: "Mandario Průvodce",
    image: "/web_resume/mandario-pruvodce.png",
    text: "Fullstack projekt vyvinutý pro společnost Mandario. Jedná se o interaktivního průvodce ve formě vícekrokového formuláře, kde uživatel postupně vyplní své preference a odešle je. Aplikaci jsem vyvíjel kompletně sám pomocí frameworku Next.js. Součástí technického řešení je také napojení na Ecomail API pro automatické odesílání e-mailů.",
    techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
    links: [{ url: "https://pruvodceedp.mandario.eu/", text: "Navšívit web" }],
  },
  {
    year: 2025,
    name: "Dům u Agáty",
    image: "/web_resume/dumuagaty.png",
    text: "Prezentační web pro dům pro seniory, který obsahuje veškeré informace pro potenciální klienty, včetně kalkulačky pobytu a online formuláře k žádosti o přijetí. Řešení využívá WordPress Customize API, což klientovi umožňuje dynamicky upravovat ceník, galerii a kontakty. Na projektu jsem působil jako Tech Lead, navrhoval jsem celkovou architekturu, prováděl code reviews a dohlížel na čistotu kódu i dodržování best practices při vývoji vlastní WordPress šablony.",
    techstack: ["PHP", "Wordpress", "Custom Theme"],
    links: [{ url: "https://dumuagaty.cz", text: "Navšívit web" }],
  },
  {
    year: 2024,
    name: "flowstate",
    image: "/web_resume/flowstate.png",
    text: "Prezentační fullstack web pro společnost flowstate, který představuje samotnou firmu, její služby a tým. Celý projekt jsem vyvíjel samostatně s využitím frameworku Next.js. Součástí technického řešení je také integrace Ecomail API pro bezproblémové zpracování a odesílání zpráv z kontaktního formuláře.",
    techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
    links: [{ url: "https://www.flowstate.cz", text: "Navšívit web" }],
  },
  {
    year: 2024,
    name: "Rebels Team Prague",
    image: "/web_resume/rebelsteamprague.png",
    text: "Fullstack aplikace na míru pro sportovní klub, vyvíjená v rámci týmu. Skládá se z veřejného webu s informacemi o lekcích a akcích a z administračního rozhraní pro správce (kompletní CRUD operace pro lekce, rozvrhy, události a další). Součástí řešení je i přímé napojení na Fakturoid pro automatické generování faktur k přihláškám.",
    techstack: ["PHP", "Laravel", "React", "Tailwind", "shadCN/ui", "SQLite"],
    links: [{ url: "https://rebelsteamprague.cz/", text: "Navšívit web" }],
  },
  {
    year: 2024,
    name: "Freshstart",
    image: "/web_resume/freshstart.png",
    text: "Interní projekt pro společnost Capstone. Jde o blogovou platformu určenou ke sdílení článků z oblasti byznysu, marketingu a technologií. Web běží na WordPressu a využívá vlastní šablonu, na jejímž vývoji jsem se podílel v rámci týmu.",
    techstack: ["PHP", "Wordpress", "Custom Theme"],
    links: [{ url: "https://freshstart.cz/", text: "Navšívit web" }],
  },
  {
    year: 2023,
    name: "Czeccam",
    image: "/web_resume/czeccam.png",
    text: "Prezentační web pro Českou asociaci pro autonomní a kooperativní mobilitu. Cílem stránek je informovat návštěvníky o misi a aktivitách asociace. Web jsem vyvíjel samostatně pomocí WordPressu a Elementoru. Součástí řešení je i blogová sekce, kde si klient může sám publikovat nové články.",
    techstack: ["Wordpress", "Elementor"],
    links: [{ url: "https://www.czeccam.cz", text: "Navšívit web" }],
  },
  {
    year: 2023,
    name: "Bar Večernice",
    image: "/web_resume/barvecernice.png",
    text: "Klientský web pro bar Večernice, který jsem implementoval zcela sám na základě dodaného designu. Stránky jsou postavené na WordPressu s využitím Elementoru, díky čemuž si může klient obsah webu následně jednoduše upravovat a spravovat sám.",
    techstack: ["Wordpress", "Elementor"],
    links: [{ url: "https://barvecernice.cz", text: "Navšívit web" }],
  },
  {
    year: 2022,
    name: "AnezkaPraha",
    image: "/web_resume/anezkapraha.png",
    text: "Klientský web pro kavárnu Anežka Praha, který zákazníkům prezentuje samotný podnik. Mohou zde najít dostupné menu a kontakty. Stránky jsem vyvíjel samostatně podle grafického návrhu dodaného klientem. Technicky je web postavený na WordPressu a Elementoru. Klient si dále stránky spravuje samostatně.",
    techstack: ["Wordpress", "Elementor"],
    links: [{ url: "https://anezkapraha.cz", text: "Navšívit web" }],
  },
];
