import type { Project, SupportedLang } from "~/types";

export const PROJECTS: Record<SupportedLang, Project[]> = {
  cs: [
    {
      year: 2026,
      name: "Mandario Whitelabel",
      image: "/web_resume/mandario-whitelabel.png",
      text: "B2B e-shop vyvinutý pro společnost Mandario, zaměřený na prodej kosmetických produktů a bytové chemie. Jde o uzavřenou klientskou zónu, kde mohou uživatelé procházet zboží, vytvářet objednávky a sledovat jejich stav. Nejkomplexnější částí aplikace je kaskádový konfigurátor, který umožňuje detailní sestavení produktu na míru (výběr obalu, uzávěru, krabičky či potisku). Kompletně celý frontend aplikace jsem vyvíjel já s využitím frameworku Next.js. Aplikace komunikuje s vlastním backendem pro správu obsahu a využívá Ecomail API pro transakční e-maily.",
      techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
      links: [
        { url: "https://konfigurator.mandario.eu", text: "Navštívit web" },
      ],
    },
    {
      year: 2026,
      name: "Mandario Průvodce",
      image: "/web_resume/mandario-pruvodce.png",
      text: "Fullstack projekt vyvinutý pro společnost Mandario. Jedná se o interaktivního průvodce ve formě vícekrokového formuláře, kde uživatel postupně vyplní své preference a odešle je. Aplikaci jsem vyvíjel kompletně sám pomocí frameworku Next.js. Součástí technického řešení je také napojení na Ecomail API pro automatické odesílání e-mailů.",
      techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
      links: [
        { url: "https://pruvodceedp.mandario.eu/", text: "Navštívit web" },
      ],
    },
    {
      year: 2025,
      name: "Dům u Agáty",
      image: "/web_resume/dumuagaty.png",
      text: "Prezentační web pro dům pro seniory, který obsahuje veškeré informace pro potenciální klienty, včetně kalkulačky pobytu a online formuláře k žádosti o přijetí. Řešení využívá WordPress Customize API, což klientovi umožňuje dynamicky upravovat ceník, galerii a kontakty. Na projektu jsem působil jako Tech Lead, navrhoval jsem celkovou architekturu, prováděl code reviews a dohlížel na čistotu kódu i dodržování best practices při vývoji vlastní WordPress šablony.",
      techstack: ["PHP", "Wordpress", "Custom Theme"],
      links: [{ url: "https://dumuagaty.cz", text: "Navštívit web" }],
    },
    {
      year: 2024,
      name: "flowstate",
      image: "/web_resume/flowstate.png",
      text: "Prezentační fullstack web pro společnost flowstate, který představuje samotnou firmu, její služby a tým. Celý projekt jsem vyvíjel samostatně s využitím frameworku Next.js. Součástí technického řešení je také integrace Ecomail API pro bezproblémové zpracování a odesílání zpráv z kontaktního formuláře.",
      techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
      links: [{ url: "https://www.flowstate.cz", text: "Navštívit web" }],
    },
    {
      year: 2024,
      name: "Rebels Team Prague",
      image: "/web_resume/rebelsteamprague.png",
      text: "Fullstack aplikace na míru pro sportovní klub, vyvíjená v rámci týmu. Skládá se z veřejného webu s informacemi o lekcích a akcích a z administračního rozhraní pro správce (kompletní CRUD operace pro lekce, rozvrhy, události a další). Součástí řešení je i přímé napojení na Fakturoid pro automatické generování faktur k přihláškám.",
      techstack: ["PHP", "Laravel", "React", "Tailwind", "shadCN/ui", "SQLite"],
      links: [{ url: "https://rebelsteamprague.cz/", text: "Navštívit web" }],
    },
    {
      year: 2024,
      name: "Freshstart",
      image: "/web_resume/freshstart.png",
      text: "Interní projekt pro společnost Capstone. Jde o blogovou platformu určenou ke sdílení článků z oblasti byznysu, marketingu a technologií. Web běží na WordPressu a využívá vlastní šablonu, na jejímž vývoji jsem se podílel v rámci týmu.",
      techstack: ["PHP", "Wordpress", "Custom Theme"],
      links: [{ url: "https://freshstart.cz/", text: "Navštívit web" }],
    },
    {
      year: 2023,
      name: "Czeccam",
      image: "/web_resume/czeccam.png",
      text: "Prezentační web pro Českou asociaci pro autonomní a kooperativní mobilitu. Cílem stránek je informovat návštěvníky o misi a aktivitách asociace. Web jsem vyvíjel samostatně pomocí WordPressu a Elementoru. Součástí řešení je i blogová sekce, kde si klient může sám publikovat nové články.",
      techstack: ["Wordpress", "Elementor"],
      links: [{ url: "https://www.czeccam.cz", text: "Navštívit web" }],
    },
    {
      year: 2023,
      name: "Bar Večernice",
      image: "/web_resume/barvecernice.png",
      text: "Klientský web pro bar Večernice, který jsem implementoval zcela sám na základě dodaného designu. Stránky jsou postavené na WordPressu s využitím Elementoru, díky čemuž si může klient obsah webu následně jednoduše upravovat a spravovat sám.",
      techstack: ["Wordpress", "Elementor"],
      links: [{ url: "https://barvecernice.cz", text: "Navštívit web" }],
    },
    {
      year: 2022,
      name: "AnezkaPraha",
      image: "/web_resume/anezkapraha.png",
      text: "Klientský web pro kavárnu Anežka Praha, který zákazníkům prezentuje samotný podnik. Mohou zde najít dostupné menu a kontakty. Stránky jsem vyvíjel samostatně podle grafického návrhu dodaného klientem. Technicky je web postavený na WordPressu a Elementoru. Klient si dále stránky spravuje samostatně.",
      techstack: ["Wordpress", "Elementor"],
      links: [{ url: "https://anezkapraha.cz", text: "Navštívit web" }],
    },
  ],
  en: [
    {
      year: 2026,
      name: "Mandario Whitelabel",
      image: "/web_resume/mandario-whitelabel.png",
      text: "A B2B e-commerce platform developed for Mandario, specializing in cosmetic products and household chemicals. It features a gated client portal where users can browse products, place orders, and track their status. The core of the application is a cascading configurator enabling detailed product customization (selection of packaging, closure, box, and print). I developed the entire frontend using Next.js. The application communicates with a custom content management backend and integrates the Ecomail API for transactional emails.",
      techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
      links: [
        { url: "https://konfigurator.mandario.eu", text: "Visit website" },
      ],
    },
    {
      year: 2026,
      name: "Mandario Průvodce",
      image: "/web_resume/mandario-pruvodce.png",
      text: "A full-stack project developed for Mandario featuring an interactive multi-step guide where users specify their preferences and submit inquiries. I built the entire application independently using Next.js. The technical solution also includes an integration with the Ecomail API for automated email delivery.",
      techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
      links: [
        { url: "https://pruvodceedp.mandario.eu/", text: "Visit website" },
      ],
    },
    {
      year: 2025,
      name: "Dům u Agáty",
      image: "/web_resume/dumuagaty.png",
      text: "A promotional website for a retirement home providing comprehensive information for prospective clients, including a stay cost calculator and an online admission application form. The solution utilizes the WordPress Customize API, enabling the client to dynamically manage pricing, galleries, and contact details. I served as Tech Lead on this project, designing the overall architecture, conducting code reviews, and ensuring clean code and best practices during the development of a custom WordPress theme.",
      techstack: ["PHP", "Wordpress", "Custom Theme"],
      links: [{ url: "https://dumuagaty.cz", text: "Visit website" }],
    },
    {
      year: 2024,
      name: "flowstate",
      image: "/web_resume/flowstate.png",
      text: "A full-stack promotional website for flowstate showcasing the agency, its services, and the team. I built the entire project independently using Next.js. The solution also includes an integration with the Ecomail API for seamless handling and delivery of contact form submissions.",
      techstack: ["NextJS", "Typescript", "Tailwind", "shadCN/ui"],
      links: [{ url: "https://www.flowstate.cz", text: "Visit website" }],
    },
    {
      year: 2024,
      name: "Rebels Team Prague",
      image: "/web_resume/rebelsteamprague.png",
      text: "A custom full-stack application for a sports club, developed collaboratively in a team. It consists of a public-facing website with information on classes and events, along with an administrative dashboard for managers (full CRUD operations for classes, schedules, events, and more). The solution also features a direct integration with Fakturoid for automated invoice generation for registrations.",
      techstack: ["PHP", "Laravel", "React", "Tailwind", "shadCN/ui", "SQLite"],
      links: [{ url: "https://rebelsteamprague.cz/", text: "Visit website" }],
    },
    {
      year: 2024,
      name: "Freshstart",
      image: "/web_resume/freshstart.png",
      text: "An internal project for Capstone. A blogging platform designed for sharing articles on business, marketing, and technology. The website runs on WordPress with a custom theme that I co-developed as part of a team.",
      techstack: ["PHP", "Wordpress", "Custom Theme"],
      links: [{ url: "https://freshstart.cz/", text: "Visit website" }],
    },
    {
      year: 2023,
      name: "Czeccam",
      image: "/web_resume/czeccam.png",
      text: "A presentation website for the Czech Association for Autonomous and Cooperative Mobility, created to introduce the association's mission and activities. I built the site independently using WordPress and Elementor. It also includes a blog section where the client can self-publish articles.",
      techstack: ["Wordpress", "Elementor"],
      links: [{ url: "https://www.czeccam.cz", text: "Visit website" }],
    },
    {
      year: 2023,
      name: "Bar Večernice",
      image: "/web_resume/barvecernice.png",
      text: "A client website for Bar Večernice, implemented independently based on provided designs. The site is built on WordPress using Elementor, allowing the client to easily manage and update content on their own.",
      techstack: ["Wordpress", "Elementor"],
      links: [{ url: "https://barvecernice.cz", text: "Visit website" }],
    },
    {
      year: 2022,
      name: "AnezkaPraha",
      image: "/web_resume/anezkapraha.png",
      text: "A client website for the café Anežka Praha, showcasing the venue, menu, and contact details. I built the website independently based on graphic designs provided by the client, utilizing WordPress and Elementor so the client can manage the site autonomously.",
      techstack: ["Wordpress", "Elementor"],
      links: [{ url: "https://anezkapraha.cz", text: "Visit website" }],
    },
  ],
};
